### PR TITLE
feat: set proc title to flashfocus if setproctitle lib present

### PR DESCRIPTION
**Pull request by cyrinux**

### CODE REVIEW

**Comment by fennerm** [comment]
Sorry @cyrinux I realize this PR has been sitting for a long time. If you are still interested in getting this merged, could you give a little background on the motivation for the change?

**Comment by cyrinux** [comment]
Hi @fennerm it was just comestic to cleanup my ps tree 😁
You can close or merge, don't worry.

**Review by Artturin — APPROVED** [review]

**Comment by fennerm** [comment]
Okay I'm gonna go ahead and close this one @cyrinux. Reticent to add an external dependency unless the benefit is clear. If anyone disagrees, please feel free to comment on the PR and we can revisit. Thanks for going to the trouble of making the PR :pray:

**Comment by cyrinux** [comment]
No problem but it was an optional dep 😉

**Comment by fennerm** [comment]
Yeah totally understood. There's still a cost there as we'd need to support it and fix bugs from upstream. As I say, its totally something we can support if you or others can make a case for why its needed :)

**Pull request closed without merging**
